### ISSUE TITLE
Error during live indexing of changes saved to user workspace

### ISSUE THREAD

**Issue by kdambekalns** [ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer#11]
When a change is saved to a user workspace, the live indexing queue is filled. When the created job is being worked on, an exception is raised:

`Exception in line 403 of /var/www/cms/Packages/Libraries/doctrine/orm/lib/Doctrine/ORM/EntityManager.php: The identifier name is missing for a query of Neos\ContentRepository\Domain\Model\Workspace - See also: 20170518132608fbe4ff.txt`

This is the trace:

    Exception in line 403 of /var/www/cms/Packages/Libraries/doctrine/orm/lib/Doctrine/ORM/EntityManager.php: The identifier name is missing for a query of Neos\ContentRepository\Domain\Model\Workspace
    
    38 Doctrine\ORM\ORMException::missingIdentifierField("Neos\ContentRepository\Domain\Model\Workspace", "name")
    37 Doctrine\ORM\EntityManager::find("Neos\ContentRepository\Domain\Model\Workspace", array|1|)
    36 Neos\Flow\Persistence\Doctrine\PersistenceManager_Original::getObjectByIdentifier(NULL, "Neos\ContentRepository\Domain\Model\Workspace")
    35 Neos\Flow\Persistence\Repository::findByIdentifier(NULL)
    34 call_user_func_array(array|2|, array|1|)
    33 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call("findByIdentifier", array|1|)
    32 Neos\ContentRepository\Domain\Service\Context_Original::getWorkspace()
    31 Neos\ContentRepository\Domain\Service\Context_Original::getNodeByIdentifier("fa08cdd4-1ee4-3b63-0916-ff08239c5d89")
    30 Flowpack\ElasticSearch\ContentRepositoryAdaptor\Indexer\NodeIndexer_Original::Flowpack\ElasticSearch\ContentRepositoryAdaptor\Indexer\{closure}(Neos\ContentRepository\Domain\Model\Node, Neos\ContentRepository\Domain\Service\Context)
    29 Flowpack\ElasticSearch\ContentRepositoryAdaptor\Indexer\NodeIndexer_Original::indexNode(Neos\ContentRepository\Domain\Model\Node)
    28 Flowpack\ElasticSearch\ContentRepositoryQueueIndexer\IndexingJob_Original::Flowpack\ElasticSearch\ContentRepositoryQueueIndexer\{closure}()
    27 Closure::__invoke()
    26 Flowpack\ElasticSearch\ContentRepositoryAdaptor\Indexer\NodeIndexer_Original::withBulkProcessing(Closure)
    25 call_user_func_array(array|2|, array|1|)
    24 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call("withBulkProcessing", array|1|)
    23 Flowpack\ElasticSearch\ContentRepositoryQueueIndexer\IndexingJob_Original::execute(Flowpack\JobQueue\Redis\Queue\RedisQueue, Flowpack\JobQueue\Common\Queue\Message)
    22 Flowpack\JobQueue\Common\Job\JobManager_Original::executeJobForMessage(Flowpack\JobQueue\Redis\Queue\RedisQueue, Flowpack\JobQueue\Common\Queue\Message)
    21 call_user_func_array(array|2|, array|2|)
    20 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call("executeJobForMessage", array|2|)
    19 Flowpack\JobQueue\Common\Command\JobCommandController_Original::executeCommand(Flowpack\JobQueue\Redis\Queue\RedisQueue, "TzozODoiRmxvd3BhY2tcSm9iUXVldWVcQ29tbW9uXFF1ZXVlXE…19IjtzOjE5OiIAKgBudW1iZXJPZlJlbGVhc2VzIjtpOjA7fQ==")
    18 call_user_func_array(array|2|, array|2|)
    17 Neos\Flow\Cli\CommandController_Original::callCommandMethod()
    16 Neos\Flow\Cli\CommandController_Original::processRequest(Neos\Flow\Cli\Request, Neos\Flow\Cli\Response)
    15 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(Neos\Flow\Cli\Request, Neos\Flow\Cli\Response)
    14 Neos\Flow\Mvc\Dispatcher_Original::dispatch(Neos\Flow\Cli\Request, Neos\Flow\Cli\Response)
    13 Neos\Flow\Cli\CommandRequestHandler::Neos\Flow\Cli\{closure}()
    12 Closure::__invoke()
    11 Neos\Flow\Security\Context_Original::withoutAuthorizationChecks(Closure)
    10 Neos\Flow\Security\Context::withoutAuthorizationChecks(Closure)
    9 call_user_func_array(array|2|, array|1|)
    8 Neos\Flow\Security\Context::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
    7 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
    6 Neos\Flow\Session\Aspect\LazyLoadingAspect_Original::callMethodOnOriginalSessionObject(Neos\Flow\Aop\JoinPoint)
    5 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
    4 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
    3 Neos\Flow\Security\Context::withoutAuthorizationChecks(Closure)
    2 Neos\Flow\Cli\CommandRequestHandler::handleRequest()
    1 Neos\Flow\Core\Bootstrap::run()

My guess: the target workspace can be null and is passed as is to the job in https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/blob/3.0/Classes/Flowpack/ElasticSearch/ContentRepositoryQueueIndexer/Indexer/NodeIndexer.php#L45 which later leads to the problem.

**Comment by kdambekalns** [comment]
I am further investigating this now…

**Comment by dfeyer** [comment]
I close this one as #13 is merged now
