### ISSUE TITLE
Error during live indexing while trying to index deleted nodes

### ISSUE THREAD

**Issue by peterbucher** [ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer#14]
When one ore more nodes are deleted and live indexing runs, an exception is raised:

`Exception: Argument 1 passed to Neos\ContentRepository\Domain\Factory\NodeFactory_Original::createFromNodeData() must be an instance of Neos\ContentRepository\Domain\Model\NodeData, null given`

I suspect, "$nodeData" (https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/blob/3.0/Classes/Flowpack/ElasticSearch/ContentRepositoryQueueIndexer/IndexingJob.php#L102) is null because they deleted node is no longer found in the repository.

Trace:
```
Exception: Argument 1 passed to Neos\ContentRepository\Domain\Factory\NodeFactory_Original::createFromNodeData() must be an instance of Neos\ContentRepository\Domain\Model\NodeData, null given
 
31 Neos\ContentRepository\Domain\Factory\NodeFactory_Original::createFromNodeData(NULL, Neos\Neos\Domain\Service\ContentContext)
30 call_user_func_array(array|2|, array|2|)
29 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call("createFromNodeData", array|2|)
28 Flowpack\ElasticSearch\ContentRepositoryQueueIndexer\IndexingJob_Original::Flowpack\ElasticSearch\ContentRepositoryQueueIndexer\{closure}()
27 Closure::__invoke()
26 Flowpack\ElasticSearch\ContentRepositoryAdaptor\Indexer\NodeIndexer_Original::withBulkProcessing(Closure)
25 call_user_func_array(array|2|, array|1|)
24 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call("withBulkProcessing", array|1|)
23 Flowpack\ElasticSearch\ContentRepositoryQueueIndexer\IndexingJob_Original::execute(Flowpack\JobQueue\Redis\Queue\RedisQueue, Flowpack\JobQueue\Common\Queue\Message)
22 Flowpack\JobQueue\Common\Job\JobManager_Original::executeJobForMessage(Flowpack\JobQueue\Redis\Queue\RedisQueue, Flowpack\JobQueue\Common\Queue\Message)
21 call_user_func_array(array|2|, array|2|)
20 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call("executeJobForMessage", array|2|)
19 Flowpack\JobQueue\Common\Command\JobCommandController_Original::executeCommand(Flowpack\JobQueue\Redis\Queue\RedisQueue, "TzozODoiRmxvd3BhY2tcSm9iUXVldWVcQ29tbW9uXFF1ZXVlXE…19IjtzOjE5OiIAKgBudW1iZXJPZlJlbGVhc2VzIjtpOjA7fQ==")
18 call_user_func_array(array|2|, array|2|)
17 Neos\Flow\Cli\CommandController_Original::callCommandMethod()
16 Neos\Flow\Cli\CommandController_Original::processRequest(Neos\Flow\Cli\Request, Neos\Flow\Cli\Response)
15 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(Neos\Flow\Cli\Request, Neos\Flow\Cli\Response)
14 Neos\Flow\Mvc\Dispatcher_Original::dispatch(Neos\Flow\Cli\Request, Neos\Flow\Cli\Response)
13 Neos\Flow\Cli\CommandRequestHandler::Neos\Flow\Cli\{closure}()
12 Closure::__invoke()
11 Neos\Flow\Security\Context_Original::withoutAuthorizationChecks(Closure)
10 Neos\Flow\Security\Context::withoutAuthorizationChecks(Closure)
9 call_user_func_array(array|2|, array|1|)
8 Neos\Flow\Security\Context::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
7 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
6 Neos\Flow\Session\Aspect\LazyLoadingAspect_Original::callMethodOnOriginalSessionObject(Neos\Flow\Aop\JoinPoint)
5 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
4 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
3 Neos\Flow\Security\Context::withoutAuthorizationChecks(Closure)
2 Neos\Flow\Cli\CommandRequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()
```

**Comment by kdambekalns** [comment]
Working on this right now, the immediate error can be solved by ignoring indexing requests for which the `NodeData` cannot be fetched. But I guess we should add a `RemovalJob` to actually process the removal in the queue as well.

**Comment by kdambekalns** [comment]
So, when skipping nodes as described above, the error is gone, but the related content is not removed from the index.

**Comment by kdambekalns** [comment]
So, removals are currently handled synchronously, this can be changed using a new `RemovalJob` as mentioned.

But the problem with removed content staying in the index needs to be solved during publishing - where each published node is sent to the indexing. It ends up in a job, but when that job is to be executed, the NodeData instance that was "memorized" is gone…

Since we don't have the node anymore, we'd need to change the way indexing works. Some of the parts expect a `NodeInterface`, but for removal we'd just need this:

    $documentIdentifier = $this->calculateDocumentIdentifier($node, $targetWorkspaceName);
    $this->currentBulkRequest[] = $this->documentDriver->delete($node, $documentIdentifier);
    $this->currentBulkRequest[] = $this->indexerDriver->fulltext($node, [], $targetWorkspaceName);

The `delete()` method uses the `$node` only to fetch the node type, that could be adjusted. `fulltext()` is another beast, though. This looks like it would need a bunch of changes, or (probably easier) some new code to remove parts from the fulltext solely based on an identifier.

Feedback welcome.

**Comment by kdambekalns** [comment]
For reference, this is what I currently have: https://github.com/kdambekalns/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/compare/bugfix/11-realtime-indexing...kdambekalns:bugfix/14-realtime-removal

**Comment by dfeyer** [comment]
@kdambekalns I like the solution, can you push a PR with this change for the branch 3.0 ?

**Comment by kdambekalns** [comment]
@dfeyer Did you see #15? That is the PR you asked for.

**Comment by kdambekalns** [comment]
So, I looked at this again, and I think we could solve this in two ways:

- adjust the CR adaptor to be able to remove a node without an instance being passed in
- adjust the queue indexer to build a "fake" node in the RemovalJob

The former makes this more stable, but might require more work. OTOH the needed refactoring might be useful anyway.

The latter would encapsulate that behaviour where it is needed, so it seems slightly more appealing to fix this issues.

Again, feedback very welcome!

**Comment by dfeyer** [comment]
> adjust the queue indexer to build a "fake" node in the RemovalJob

It's not an option we don't have enough informations to build a fake node (node type, workspace, ...) , even if we adapt the RemovalJob to have enough informations, we need to adapt the IndexingJob too (because this can happens in the indexing job, you know ordering in distributed systems)

> adjust the CR adaptor to be able to remove a node without an instance being passed in

We touch public interface there ... so major release required ... and we have so many release of this package that I will avoid creating a new one ;)

So this is a nasty issue 😜

**Comment by dfeyer** [comment]
Can you check my last commit and comment here https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/pull/15#issuecomment-338053967
