### ISSUE TITLE
Multiple job worker seem not to scale

### ISSUE THREAD

**Issue by obi12341** [ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer#2]
Hello,

we are using your supervisord config and getting a lot of errors like this:

```

Cannot delete job 88: NOT_FOUND

  Type: Pheanstalk\Exception\ServerException
  File: Packages/Libraries/pda/pheanstalk/src/Command/DeleteCommand.php
  Line: 44
```

Seems like the daemons (job:work) are working on the same job and not on 12 diffrent job. Is this true? Any way to solve this? Because it doesn't scale with multiple jobs like it should be.

**Comment by dfeyer** [comment]
Really strange we use the package with supervisord + beanstalkd with 8 workers, and we don't have a single error message like yours. Did you have a more complet exception stack trace ?

**Comment by dfeyer** [comment]
@obi12341 After crawling our logs, we have a few error message per day, what's the ratio of error / success jobs for you ?

It look like we have more message like this when the server is under high load.
