### ISSUE TITLE
Version 3.0.1 was tagged off of master branch, not 3.0 branch

### ISSUE THREAD

**Issue by kdambekalns** [ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer#23]

**Comment by kdambekalns** [comment]
@dfeyer said this in Slack:

> What about "removing" the branch 3.0 ? Master will be the new 3.0 ... or commit in master will not be release before ... 4.x

**Comment by kdambekalns** [comment]
To which I respond: fine with me, good to know. Removing the branch might break things for people using it, though.

It's just important to know. So…

- anything in 3.0 should be merged in to master now
- open PRs be changed to target master
- a branch-alias for 3.0 can be added to master
- then remove the 3.0 branch

**Comment by dfeyer** [comment]
- [x] anything in 3.0 should be merged in to master now
- [ ] open PRs be changed to target master
- [ ] a branch-alias for 3.0 can be added to master
- [ ] then remove the 3.0 branch

Upmerge 3.0 -> master has beed done before the last release

**Comment by dfeyer** [comment]
@kdambekalns is this enough https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/pull/27/files

**Comment by kdambekalns** [comment]
Yup, looks good!
