### ISSUE TITLE
Update needed?

### ISSUE THREAD

**Issue by knusperpixel** [ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer#5]
Hi!
I was trying to use this package, but there was an error.
It seems that `TYPO3\Jobqueue` was renamed to `Flowpack\JobQueue`?

I had to change some lines and after that it worked.

**Comment by knusperpixel** [comment]
Oh, i just saw this pull request https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/pull/4

This seems to be related.
I can confirm that this package works with the Flowpack JobQueue

**Comment by VimS** [comment]
Also:
 composer require typo3/jobqueue-beanstalkd
This package is abandoned and no longer maintained. The author suggests using the flowpack/jobqueue-beanstalkd package instead.

**Comment by kdambekalns** [comment]
This is solved… @dfeyer, could you please close this? ;)
