### ISSUE TITLE
Make Queuename configurable

### ISSUE THREAD

**Issue by knusperpixel** [ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer#6]
I think it would be nice if the queuename was configurable.
I am using this package with the Doctrine Backend and Doctrine did not like the default queuename `Flowpack.ElasticSearch.ContentRepositoryQueueIndexer`. The dots mixed up the SQL.

**Comment by dfeyer** [comment]
Hi @knusperpixel sorry for the delay, I don't plan to make the index queue configurable, it's purely internal. Look like your issue is more in the Doctrine Backend, I don't see a technical argument to not support dots in the queue name ...
